- hosts: name_node
  - vars:
     folder: "nn"
     node: "name"
     ip: "192.168.43.46"
     port: "9001"
      
  tasks:
    - name: copying rpm files
      copy:
        src: "/ws1/{{ item }}"
        dest: "/root/"
      loop:
        - "jdk-8u171-linux-x64.rpm"
        - "hadoop-1.2.1-1.x86_64.rpm"

    - name: Installing softwares
      package:
        name: 
           - "jdk-8u171-linux-x64.rpm"
           - "hadoop-1.2.1-1.x86_64.rpm"
        state: present

    - name: Creating folder to contribute in cluster
      file:
         path: /{{ folder }}
         state: directory
    
    - name: Configuring Files
      template:
        dest: "/etc/hadoop/"
        src: "/hadoop-ansible/{{ item }}"
      loop:
       - "hdfs-site.xml"
       - "core-site.xml"

    - name: Starting Namenode Services
      shell: "hadoop-daemon.sh start {{ node }}node"
