---
# tasks file for slave-node

  - name: Installing packages
    package:
       name: "{{ item  }}"
       state: present
    loop:
      - docker
      - iproute-tc

  - name: Updating Docker cgroup driver
    copy:
      dest: /etc/docker/daemon.json
      content: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"]
        }

  - name: Copying the yum repo for Kubernates
    copy:
      dest: /etc/yum.repos.d/kubernetes.repo
      src: /ws3/kubernetes.repo

  - name: Installing kubectl, kubeadm & kubelet packages
    shell: "yum install -y kubectl kubeadm kubelet --disableexcludes=kubernetes"

  - name: Starting the docker & kubelet services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - docker
      - kubelet

  - name: Updating Docker cgroup driver
    copy:
      dest: /etc/sysctl.d/k8s.conf
      content: |
        {
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
        }

  - name: Joining the Master
    shell: "{{ hostvars[item]['cjoin']['stdout'] }}"
    with_items: "{{ groups['tag_node_master'] }}"
